# Server
server.port=${PORT:8081}

# Database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# App
spring.application.name=ember

#jwtAuth
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

# OpenAI API (for nudges and insights)
openai.api.key=${openai.api.key:}

logging.level.com.ember.backend=INFO